
version: 2

models:
    - name: customer
      columns:
          - name: customer_id
            tests:
                - unique
                - not_null
    - name: customer_tgt
      columns:
          - name: customer_id
            tests:
                - unique
                - not_null

                


